spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:http://localhost:8888
  app:
    jwtSecret: mySecretKey123912738fsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfgfdhrher
    jwtExpirationMs: 3000000
  ecom:
    app:
      jwtCookieName: springBootEcom



  cloud:
    gateway:
      routes:
        - id: product-manager
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-manager/**
          filters:
            - RewritePath=/product-manager/(?<segment>.*), /$\{segment}
        - id: user-manager
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-manager/**
          filters:
            - RewritePath=/user-manager/(?<segment>.*), /$\{segment}
        - id: order-manager
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order-manager/**
          filters:
            - RewritePath=/order-manager/(?<segment>.*), /$\{segment}
        - id: eureka-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/main
          filters:
            - SetPath=/
        - id: eureka-server-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:5173"
              - "${frontend.url}"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
              - PATCH
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600

gateway:
  security:
    public-paths:
      - /user-manager/api/auth/**
      - /user-manager/api/public/**
      - /product-manager/api/public/**
      - /product-manager/images/**
      - /order-manager/api/public/**
      - /order-manager/api/internal/**
      - /eureka/**
      - /v3/api-docs/**
      - /swagger-ui/**

    role-mappings: []
#    role-mappings:
#      - pattern: /product-manager/api/admin/**
#        roles: [ROLE_ADMIN]
#      - pattern: /product-manager/api/products/**
#        roles: [ROLE_SELLER, ROLE_ADMIN]
#      - pattern: /order-manager/api/carts/**
#        roles: [ROLE_USER, ROLE_ADMIN]
#      - pattern: /order-manager/api/order/**
#        roles: [ROLE_USER, ROLE_ADMIN]
#      - pattern: /user-manager/api/addresses/**
#        roles: [ROLE_USER, ROLE_ADMIN]
#      - pattern: /user-manager/api/users/addresses/**
#        roles: [ROLE_USER, ROLE_ADMIN]
#      - pattern: /user-manager/api/admin/**
#        roles: [ROLE_ADMIN]

server:
  port: 8080

frontend:
  url: http://localhost:5173