spring:
  datasource:
    url: jdbc:mysql://localhost:3306/laptop_ecommerce_graduation_project_product_service?serverTimezone=UTC
    username: root
    password: thailam123

  jpa:
    hibernate:
      ddl-auto: update

  app:
    jwtSecret: mySecretKey123912738fsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfsdfgfdhrher
    jwtExpirationMs: 3000000
  ecom:
    app:
      jwtCookieName: springBootEcom

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

project:
  image: images/

image:
  base:
    url: http://localhost:8080/product-manager/images
#    url: https://springfield-baskets-cream-apt.trycloudflare.com/product-manager/images  # Backend tunnel URL
server:
  port: 8081

frontend:
  url: http://localhost:5173
#  url: https://pictures-rebate-mine-made.trycloudflare.com  # Frontend tunnel URL

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true